// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualExcursion.DAL.context;

#nullable disable

namespace VirtualExcursion.DAL.Migrations
{
    [DbContext(typeof(VExContext))]
    partial class VExContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VirtualExcursion.DAL.models.GuideProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GuideProfiles");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.ModelScene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmbientLightIntensity")
                        .HasColumnType("float");

                    b.Property<double>("CameraStartX")
                        .HasColumnType("float");

                    b.Property<double>("CameraStartY")
                        .HasColumnType("float");

                    b.Property<double>("CameraStartZ")
                        .HasColumnType("float");

                    b.Property<double>("CameraTargetX")
                        .HasColumnType("float");

                    b.Property<double>("CameraTargetY")
                        .HasColumnType("float");

                    b.Property<double>("CameraTargetZ")
                        .HasColumnType("float");

                    b.Property<bool>("EnableVR")
                        .HasColumnType("bit");

                    b.Property<string>("ModelFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<string>("modelUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SceneId")
                        .IsUnique();

                    b.ToTable("ModelScenes");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.POI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CoordinateX")
                        .HasColumnType("float");

                    b.Property<double>("CoordinateY")
                        .HasColumnType("float");

                    b.Property<double>("CoordinateZ")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModelSceneId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelSceneId");

                    b.HasIndex("SceneId");

                    b.ToTable("PointsOfInterest");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ContentType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsPublished", "CreatedAt");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.SceneTag", b =>
                {
                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("SceneId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("SceneTags");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.GuideProfile", b =>
                {
                    b.HasOne("VirtualExcursion.DAL.models.User", "User")
                        .WithOne("GuideProfile")
                        .HasForeignKey("VirtualExcursion.DAL.models.GuideProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.ModelScene", b =>
                {
                    b.HasOne("VirtualExcursion.DAL.models.Scene", "Scene")
                        .WithOne("ModelScene")
                        .HasForeignKey("VirtualExcursion.DAL.models.ModelScene", "SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.POI", b =>
                {
                    b.HasOne("VirtualExcursion.DAL.models.ModelScene", null)
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("ModelSceneId");

                    b.HasOne("VirtualExcursion.DAL.models.Scene", "Scene")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.Scene", b =>
                {
                    b.HasOne("VirtualExcursion.DAL.models.GuideProfile", "Author")
                        .WithMany("Scenes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.SceneTag", b =>
                {
                    b.HasOne("VirtualExcursion.DAL.models.Scene", "Scene")
                        .WithMany("SceneTags")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualExcursion.DAL.models.Tag", "Tag")
                        .WithMany("SceneTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.GuideProfile", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.ModelScene", b =>
                {
                    b.Navigation("PointsOfInterest");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.Scene", b =>
                {
                    b.Navigation("ModelScene");

                    b.Navigation("PointsOfInterest");

                    b.Navigation("SceneTags");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.Tag", b =>
                {
                    b.Navigation("SceneTags");
                });

            modelBuilder.Entity("VirtualExcursion.DAL.models.User", b =>
                {
                    b.Navigation("GuideProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
